language: java
os: linux
dist: xenial

jdk:
    - openjdk11

install: true

addons:
  sonarcloud:
    organization: d0543027-github
    token:
      secure: 6a6c287a2c178cee8a86b7d486550ad9a8144891 # encrypted value of your token

script:
    - gradle clean
    - gradle check
    - gradle sonarqube
    - gradle build
