language: java
os: linux
dist: xenial

jdk:
    - openjdk11

install:
    - gradle assemble

script:
    - gradle test
    - gradle sonarqube -Dsonar.host.url=$SONAR_LOCAL_HOST -Dsonar.login=$SONAR_LOCAL_TOKEN
