language: java
os: linux
dist: xenial

jdk:
    - openjdk11

install: true

addons:
  sonarcloud:
    organization: d0543027
    token:
      secure: 2415f8b23f3fc51d8621ace562e248e18b2b66ed

script:
    - gradle clean
    - gradle check
    - gradle build
    - gradle sonarqube -Dsonar.login=$SONAR_TOKEN_2
