language: java
os: linux
dist: xenial

jdk:
    - openjdk11

install: true

addons:
  sonarcloud:
    organization: d0543027-github
    token:
      secure: meCybwCfSFOZJM6C/d+WswTFXJdktMW5plFqZ1oDrJQU8pjZvuLmgKOiyJDU7TqnEUWevDddXWDWVHBvjOd3972vP8//MRbAAfJ41gXYwdAecFKOMvvknmXevGwskksPU0A6htDbJAWhYWxe91sb42PqizyAitwTmW3LhrNHBHq+JeXSwSlRnqogeeOJsn/h1EvSHAz9Mfk6C6bn/Lo3RwB7UlQWtXq9aU1VY5a/FP91o6/tG8lruq9F+B0yh1LRRARA867Nqr70GjUulfzCqL9jth1gmFj9DzKcp6UypPkaq1aWp0ETxjl+x6+73Majr7/yGBCzhBIapt51L3SIwjXTKkICGcZUOPj7P7lfDdpYo1z3yVjswDxsunUmzBZfm+uK9GAZA1ryGQ/1LdJKbapJJ1cXV31DlETTKSwaY/KMwwe+xhokBcrsQax50DObwlnKHNCHoR/GEz7sGve77vjhjTFlMBToWZmxtgHfLdajeUUV5NFYCypqTt14+YQWL6iVDbjlGs5ZdXZ1JTBJ23ar7b1Na6ivb1I74HthlJwumzT2ZFSvTKVmz/BKsTfJtQdtLvGx+u6WH5wHP0xZfkC1wr9Ou2PxhWkasqvLO8mjv4WtRHiTzzG87o2ruf0UJN4SQIvxj4dZ6/aEhWH6TJ+XZ7XTbxBCkJl3jVteCR4= # encrypted value of your token

script:
    - gradle clean
    - gradle check
    - gradle sonarqube
    - gradle build
